### ISSUE TITLE
Cannot reshape array

### ISSUE THREAD

**Issue by hermelino** [OscarEngelbrektson/SyntheticControlMethods#21]
I'm trying to run a synthetic control model with my data and I'm getting the error message below. Can someone help me, please?

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\SyntheticControlMethods\main.py", line 333, in __init__
    original_checked_input = self._process_input_data(
  File "C:\ProgramData\Anaconda3\lib\site-packages\SyntheticControlMethods\main.py", line 175, in _process_input_data
    control_outcome_all, control_outcome, unscaled_control_covariates = self._process_control_data(
  File "C:\ProgramData\Anaconda3\lib\site-packages\SyntheticControlMethods\main.py", line 243, in _process_control_data
    control_outcome_all = np.array(control_data_all[outcome_var]).reshape(n_controls, periods_all).T #All outcomes
ValueError: cannot reshape array of size 773 into shape (43,18)

**Comment by hermelino** [comment]
The data I'm using has all the same length, so I don't have idea how to solve this.

**Comment by rb-jet** [comment]
I had the same issue, you should check that you have a record for each combination of unit and time period. If you have a unit without a record for a given time period, you'll get this. 

Mine weren't complete, once I removed those units, it fully run
